spring:
  application:
    name: stockTradeService
  datasource:
    url: jdbc:mysql://localhost:3306/stockTrade
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # 👈 Add this to create tables
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#  security:
#    oauth2:
#      resource server:
#        jwt:
#          issuer-uri: https://dev-vadxcvucf3d58rna.us.auth0.com/
server:
  port: 8080

